name: Deploy to IIS (Self-Hosted)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Stop AppPool
      run: |
        Import-Module WebAdministration
        Stop-WebAppPool -Name "_jira.copilot"
      shell: powershell
    
    - name: Publish .NET App
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish
    
    - name: Copy files to IIS
      run: |
        $destination = "F:\inetpub\sites\jira.copilot"
        Remove-Item "$destination\*" -Recurse -Force
        Copy-Item -Path "./publish/*" -Destination $destination -Recurse -Force
    
    - name: Start AppPool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "_jira.copilot"
      shell: powershell
