name: Deploy to IIS (Self-Hosted)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Stop AppPool (if running)
      run: |
        Import-Module WebAdministration
        $poolName = "_jira.copilot"
        $pool = Get-WebAppPoolState -Name $poolName
        if ($pool.Value -eq "Started") {
            Stop-WebAppPool -Name $poolName
        }
      shell: powershell
    
    - name: Publish .NET App
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish

    - name: Copy files (exclude appsettings.json)
      run: |
        $source = "./publish"
        $destination = "F:\inetpub\sites\jira.copilot"
        robocopy $source $destination /MIR /XO /ZB /XF "appsettings.json" "appsettings.*.json" /W:1 /R:3 /NP /LOG+:deploy.log;
        if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
      shell: powershell
    
    - name: Start AppPool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "_jira.copilot"
      shell: powershell
