name: Deploy to IIS (Self-Hosted)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Stop AppPool (as Admin)
      run: |
        Start-Process -FilePath "powershell" -ArgumentList {
          Import-Module WebAdministration
          Stop-WebAppPool -Name "_jira.copilot"
        } -Verb RunAs -Wait
      shell: powershell
    
    - name: Publish .NET App
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish
    
    - name: Copy files to IIS
      run: |
        $source = "./publish"
        $destination = "F:\inetpub\sites\jira.copilot"
        Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
      shell: powershell
    
    - name: Start AppPool
      run: |
        Import-Module WebAdministration
        Start-WebAppPool -Name "_jira.copilot"
      shell: powershell
